from scavenger_hunt_with_complex_actions import main_program
from timinator import CONGRATS
import random

def send_msg(channel, msg):
    print("TECHIO> message --channel \"{}\" \"{}\"".format(channel, msg))

if __name__ == "__main__":
    main_program()
    channel = f'{random.choice(CONGRATS)} 🌟'
    
    message = 'The same four solutions are generated by this implementation.'
    
    send_msg(channel, message)
